name: integration
on:
  push:
    branches:
      - master

jobs:
  build-and-generate:
    name: echo test
    runs-on: ubuntu-latest
    steps:
    - name: My first Step
      run: echo Hello World

    - name: Checkout
      uses: actions/checkout@master
      with:
        ref: gh-pages
      